version: '3.7'
services:
  backup-management:
    image: tinhgin/backup_management
    environment:
      - TELEGRAM_BOT_TOKEN=TELEGRAM_BOT_TOKEN
      - TELEGRAM_CHAT_ID=TELEGRAM_CHAT_ID
      - PROXY=PROXY
      - DB_NAME=DB_NAME
      - DB_USER=DB_USER
      - DB_PASSWORD=DB_PASSWORD
      - DB_HOST=DB_HOST
      - DB_PORT=DB_PORT
      - EMAIL_HOST_USER=EMAIL_HOST_USER
      - EMAIL_HOST_PASSWORD=EMAIL_HOST_PASSWORD
      - MAIL_TO=MAIL_TO
      - VIEWER_PASS=VIEWER_PASS
    ports:
      - 8000:8000
    depends_on:
      - mysql

  mysql:
    image: mysql:5.7
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    volumes:
      - mysql:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: rootpw
      MYSQL_DATABASE: backup
      MYSQL_USER: backup_user
      MYSQL_PASSWORD: backuppw

#  adminer:
#    image: adminer
#    restart: always
#    ports:
#      - 8080:8080

volumes:
  mysql: