version: '3.7'
services:
  backup-management:
    image: tinhgin/backup_management
    environment:
      - TELEGRAM_BOT_TOKEN=18455xxxxx:AAFHh5eJ5JOhakPg4NCI6qc0Mxxxxxxxxxx
      - TELEGRAM_CHAT_ID=-5739xxxxx
      #- PROXY=PROXY
      - DB_NAME=xxxxx
      - DB_USER=xxxxx
      - DB_PASSWORD=xxxxx
      - DB_HOST=xxxxx
      - DB_PORT=3306
      - EMAIL_HOST_USER=example@gmail.com
      - EMAIL_HOST_PASSWORD=xxxxx
      - MAIL_TO=example1@gmail.com, example2@gmail.com
      - VIEWER_PASS=xxxxx
      - HOST=https://backup.example.com
    ports:
      - 8000:8000
    depends_on:
      - mysql

  mysql:
    image: mysql:5.7
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    volumes:
      - mysql:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: xxxxx
      MYSQL_DATABASE: xxxxx
      MYSQL_USER: xxxxx
      MYSQL_PASSWORD: xxxxx

#  adminer:
#    image: adminer
#    restart: always
#    ports:
#      - 8080:8080

volumes:
  mysql: