# Generated by Django 3.2.3 on 2021-06-16 06:47

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Backup',
            fields=[
                ('name', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('storage_type', models.CharField(choices=[('s3', 'S3'), ('fs', 'Filesystem')], default='fs', help_text='Storage type: S3 or Filesystem', max_length=2)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='FSStorage',
            fields=[
                ('server_ip', models.GenericIPAddressField(primary_key=True, serialize=False)),
                ('ssh_user', models.CharField(default='backup', max_length=50)),
                ('ssh_private_key', models.FileField(upload_to='uploads/')),
            ],
            options={
                'ordering': ['server_ip'],
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('name', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('description', models.CharField(blank=True, max_length=200)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='S3Storage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('bucket', models.CharField(max_length=100)),
                ('region', models.CharField(max_length=100)),
                ('endpoint', models.CharField(blank=True, max_length=100, null=True)),
                ('access_key_id', models.CharField(max_length=100)),
                ('secret_access_key', models.CharField(max_length=100)),
            ],
            options={
                'ordering': ['bucket'],
            },
        ),
        migrations.CreateModel(
            name='TotalBackup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True)),
                ('total', models.PositiveIntegerField(blank=True, null=True)),
            ],
            options={
                'ordering': ['date'],
            },
        ),
        migrations.CreateModel(
            name='S3Path',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('s3_path', models.CharField(max_length=100)),
                ('s3_bucket', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='main.s3storage')),
            ],
            options={
                'ordering': ['s3_path'],
            },
        ),
        migrations.CreateModel(
            name='FSPath',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('fs_path', models.CharField(max_length=100)),
                ('server_ip', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='main.fsstorage')),
            ],
            options={
                'ordering': ['fs_path'],
            },
        ),
        migrations.CreateModel(
            name='BackupInstance',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, help_text='Unique ID for this particular backup', primary_key=True, serialize=False)),
                ('file_name', models.CharField(max_length=100, unique=True)),
                ('date', models.DateTimeField(blank=True, null=True)),
                ('size', models.PositiveBigIntegerField(blank=True, null=True)),
                ('backup', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='main.backup')),
            ],
            options={
                'ordering': ['date'],
            },
        ),
        migrations.AddField(
            model_name='backup',
            name='fs_storage',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='main.fspath'),
        ),
        migrations.AddField(
            model_name='backup',
            name='project',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='main.project'),
        ),
        migrations.AddField(
            model_name='backup',
            name='s3_storage',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='main.s3path'),
        ),
    ]
